# Generated by Django 5.2.dev20241101104349 on 2024-11-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=200)),
                ('course_details', models.CharField(max_length=200)),
                ('course_pub_date', models.DateTimeField()),
            ],
        ),
    ]
