# Generated by Django 5.2.dev20241101104349 on 2024-11-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_course_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_pub_date',
            field=models.DateField(),
        ),
    ]
